#!/usr/bin/env bash

home_config_dir="$HOME/.config"
dotfiles_dir="$HOME/workspace/dotfiles"

echo "[+] Link config folder"
target_folders=("tmux" "kitty" "nvim")
for folder_name in "${target_folders[@]}"; do
  folder="$dotfiles_dir/config/$folder_name"
  target_folder="$home_config_dir/$folder_name"

  if [ -d "$target_folder" ];then
    echo "[!] Removing existing $target_folder"
    rm -rf "$target_folder"
  fi

  ln -s "$folder" "$target_folder"
  echo "[+] Created symlink from $folder to $target_folder"
done

echo "[+] Link home files"
shopt -s dotglob
for file in "$dotfiles_dir/link"/*; do
  if [ -f $file ]; then
    filename=$(basename "$file")
    rm -rf "$HOME/$filename"
    ln -s "$file" "$HOME/$filename"
    echo "Created symlink from $file to $HOME/$filename"
  fi
done
shopt -u dotglob
