#!/usr/bin/env bash

# @see https://apple.stackexchange.com/questions/10467/how-to-increase-keyboard-key-repeat-rate-on-os-x
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 10

if ! xcode-select --print-path &>/dev/null; then
  xcode-select --install &> /dev/null
  until xcode-select --print-path &> /dev/null; do
    sleep 5
  done
fi

brew_bin=$(which brew) &> /dev/null
if [[ $? != 0 ]]; then
  echo "installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [[ $? != 0 ]]; then
    echo "unable to install homebrew, abort.."
    exit 2
  fi
fi
