require('core.pack'):boot_strap()
require('core.options')
-- vim.cmd.colorscheme('gruvbox')
_G.kind_icons = {
  Array = ' ',
  Boolean = '󰨙 ',
  Class = ' ',
  Color = ' ',
  Control = ' ',
  Collapsed = ' ',
  Copilot = ' ',
  Event = ' ',
  Field = ' ',
  File = ' ',
  Folder = ' ',
  Interface = ' ',
  Key = ' ',
  Module = ' ',
  Namespace = '󰦮 ',
  Null = ' ',
  Number = '󰎠 ',
  Object = ' ',
  Operator = ' ',
  Package = ' ',
  Property = ' ',
  Reference = ' ',
  Snippet = '󱄽 ',
  String = ' ',
  Supermaven = ' ',
  TabNine = '󰏚 ',
  TypeParameter = ' ',
  Unit = ' ',
  Value = ' ',
  Text = '󰉿 ',
  Method = '󰆧 ',
  Function = '󰡱 ',
  Constructor = ' ',
  Variable = '󰀫 ',
  Enum = ' ',
  Keyword = '󰌋 ',
  EnumMember = ' ',
  Constant = '󰏿 ',
  Struct = '󰙅 ',
}
