theme = "onedark"

[editor]
auto-info = true            # whether to display info boxes
completion-timeout = 5       # default is 250ms, set to 5 for instant
cursorline = true            # highlight all lines with a cursor
default-yank-register = "+"  # use system clipboard
line-number = "relative"
inline-diagnostics.cursor-line = "hint"
smart-tab.enable = false     # tab insert tab character
soft-wrap.enable = true

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"

[keys.normal.g]
# newline without continue comment
O = ["open_above", "delete_word_backward"]
o = ["open_below", "delete_word_backward"]
# overwrite goto_first_nonwhitespace
s = "signature_help"
# a = "code_action"

[keys.normal.space]
# filter ERROR diagnostics
C-d = "@<space>D%severity ERROR "

[keys.normal]
x = "select_line_below"
X = "select_line_above"
C-s = ":write"

[keys.select.g]
s = "signature_help"
# a = "code_action"

[keys.insert]
C-f = "move_char_right"
C-b = "move_char_left"
C-a = "goto_line_start"
C-e = "goto_line_end"
