[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "cpy", "ipy", "pyt"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json", "requirements.txt", ".venv/"]
comment-token = "#"
language-servers = [{name = "basedpyright", except-features = ["diagnostics"] }, "ruff" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
python.analysis.venv = ".venv"
python.analysis.lint = true
python.analysis.inlayHint.enable = true
python.analysis.autoSearchPaths = true
python.analysis.diagnosticMode = "workspace"
python.analysis.useLibraryCodeForType = true
python.analysis.logLevel = "Error"
python.analysis.typeCheckingMode = "off"
python.analysis.autoImportCompletion = true
python.analysis.reportOptionalSubscript = false
python.analysis.reportOptionalMemberAccess = false

# markdown
[[language]]
name = "markdown"
text-width = 80
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
language-servers = ["marksman", "harper-ls"]
formatter = { command = "prettier", args = ["--parser", "markdown", "--prose-wrap", "never"]}
auto-format = true

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

# for much fewer false-positives
[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = false
SentenceCapitalization = false
